console_title_template = '{{ .Folder }}'
version = 3

[transient_prompt]
  template = ' '
  foreground = '#d2ff5e'
  background = 'transparent'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = '<transparent,#d2ff5e></>'
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}}'
    foreground = '#000000'
    background = '#d2ff5e'
    type = 'os'
    style = 'diamond'

    [blocks.segments.properties]
      macos = ' '
      ubuntu = ' '
      windows = ' '

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = '<transparent,#d2ff5e></>'
    template = ' {{ .CurrentDate | date .Format }} '
    foreground = '#000000'
    background = '#d2ff5e'
    type = 'time'
    style = 'diamond'

    [blocks.segments.properties]
      time_format = '15:04:05'

  [[blocks.segments]]
    leading_diamond = ''
    template = ' CPU: {{ round .PhysicalPercentUsed .Precision }}% | '
    foreground = '#000000'
    background = '#d2ff5e'
    type = 'sysinfo'
    style = 'diamond'

  [[blocks.segments]]
    trailing_diamond = '<transparent,#d2ff5e></>'
    template = 'RAM: {{ (div ((sub .PhysicalTotalMemory .PhysicalAvailableMemory)|float64) 1073741824.0) }}/{{ (div .PhysicalTotalMemory 1073741824.0) }}GB  '
    foreground = '#000000'
    background = '#d2ff5e'
    type = 'sysinfo'
    style = 'diamond'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .FormattedMs }} '
    foreground = '#000000'
    background = '#d2ff5e'
    type = 'executiontime'
    style = 'diamond'

    [blocks.segments.properties]
      style = 'roundrock'
      threshold = 0.0

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = '<transparent,#d2ff5e></>'
    template = ' {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}'
    foreground = '#000000'
    background = '#d2ff5e'
    type = 'node'
    style = 'diamond'

    [blocks.segments.properties]
      fetch_package_manager = true
      npm_icon = ' <#cc3a3a></> '
      yarn_icon = ' <#348cba></>'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#000000'
    background = '#d2ff5e'
    type = 'git'
    style = 'diamond'

    [blocks.segments.properties]
      branch_icon = ' '
      fetch_status = true
      fetch_upstream_icon = true
      fetch_worktree_count = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '  {{ .Path }} '
    foreground = '#d2ff5e'
    type = 'path'
    style = 'diamond'

    [blocks.segments.properties]
      folder_icon = ' '
      home_icon = '~'
      style = 'agnoster_full'

  [[blocks.segments]]
    template = ' '
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}#e48484{{end}}', '{{if eq .Code 0}}#d2ff5e{{end}}']

    [blocks.segments.properties]
      always_enabled = true

[secondary_prompt]
  template = '❯❯ '
  foreground = '#d2ff5e'
  background = 'transparent'