console_title_template = '{{ .Folder }}'
version = 3

[transient_prompt]
  template = '❯ '
  foreground = '#2e3d7c'
  background = 'transparent'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ' {{ if .SSHSession }}SSH{{ end }} '
    foreground = '#dddddd'
    background = '#d0233e'
    type = 'session'
    style = 'diamond'
    leading_diamond = '<transparent,#d0233e></>'
    trailing_diamond = ''

  [[blocks.segments]]
    template = ' {{ if .WSL }}WSL{{ end }} '
    foreground = '#dddddd'
    background = '#d0233e'
    type = 'os'
    style = 'diamond'
    leading_diamond = '<transparent,#d0233e></>'
    trailing_diamond = ''

  [[blocks.segments]]
    template = ' {{.Icon}}  '
    foreground = '#dddddd'
    background = '#333333'
    type = 'os'
    style = 'diamond'
    leading_diamond = '<transparent,#333333></>'
    trailing_diamond = ''

  [[blocks.segments]]
    template = ' {{ .UserName }}@{{ .HostName }} '
    foreground = '#dddddd'
    background = '#333333'
    type = 'session'
    style = 'diamond'
    leading_diamond = '<transparent,#333333></>'
    trailing_diamond = ''

  [[blocks.segments]]
    powerline_symbol = ''
    template = ' {{ .UpstreamIcon }}  {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#dddddd'
    background = '#d0233e'
    type = 'git'
    style = 'accordion'

    [blocks.segments.properties]
      branch_icon = '  '
      fetch_status = true
      fetch_upstream_icon = true
      fetch_worktree_count = true

 [[blocks.segments]]
    powerline_symbol = ''
    template = ''
    foreground = '#111111'
    background = 'transparent'
    type = 'text'
    style = 'accordion'

 [[blocks.segments]]
    powerline_symbol = ''
    template = '  {{ if .PackageManagerIcon }} {{ .PackageManagerIcon }} {{ end }}{{ .Full }} '
    foreground = '#111111'
    background = '#a7cc4b'
    type = 'node'
    style = 'accordion'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = '{{ if gt .Code 0 }} Exit code {{ .Code }} {{ end }}'
    foreground = '#ff8888'
    background = '#880000'
    type = 'status'
    style = 'diamond'
    trailing_diamond = ' '
    leading_diamond = ''

  [[blocks.segments]]
    template = ' {{ .FormattedMs }} '
    foreground = '#111111'
    background = '#005b99'
    type = 'executiontime'
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = '<transparent,#005b99></>'

    [blocks.segments.properties]
      style = 'roundrock'
      threshold = 100.0

  [[blocks.segments]]
    template = '  {{ .CurrentDate | date .Format }} '
    foreground = '#dddddd'
    background = '#333333'
    type = 'time'
    style = 'diamond'
    leading_diamond = ''

    [blocks.segments.properties]
      time_format = '15:04:05'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ' {{ .Path }} '
    foreground = '#dddddd'
    background = '#transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      folder_icon = '…'
      home_icon = '~'
      style = 'agnoster_full'

  [[blocks.segments]]
    template = '❯'
    type = 'status'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#ffffff'
    background_templates = ['{{if gt .Code 0}}#880000{{end}}', '{{if eq .Code 0}}#2e3d7c{{end}}']

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    template = '<b> </b>'
    foreground = '#dddddd'
    background = '#transparent'
    type = 'text'
    style = 'plain'

[secondary_prompt]
  template = '❯❯ '
  foreground = '#d2ff5e'
  background = 'transparent'
  style = 'powerline'